customer/urls.py
from django.urls import path
from customer import views

app_name = 'customer'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add-to-wishlist/<id>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/<id>/', views.remove_from_wishlist, name='remove-from-wishlist'),
    
    path('mark-notification-seen/<id>', views.mark_notification_seen, name='mark-notification-seen'),

    path('address-detail/<id>', views.address_detail, name='address-detail'),
    path('address-create/', views.address_create, name='address-create'),
    path('delete-address/<id>/', views.delete_address, name='delete-address'),

    path('update-profile/', views.update_profile, name='update-profile'),
    path('change-password/', views.change_password, name='change-password'),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from store import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user/', include('userauths.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    # HomePage
    path('', views.index, name='index'),

    # Category
    path('category/<slug>/', views.category, name='category'),

    # Product Detail
    path('product-detail/<slug>/', views.product_detail, name='product-detail'),

    # Add To Cart, Cart, Delete Cart Item
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),
    path('delete-cart-item/', views.delete_cart_item, name='delete-cart-item'),

    # Create Order, Checkout
    path('create-order/', views.create_order, name='create-order'),
    path('checkout/<order_id>/', views.checkout, name='checkout'),
    path('coupon-apply/<order_id>/', views.coupon_apply, name='coupon-apply'),

    # Payment
    path('paypal-payment-verify/<order_id>/', views.paypal_payment_verify, name='paypal-payment-verify'),
    path('payment-status/<order_id>/', views.payment_status, name='payment-status'),
    
    path('stripe-payment/<order_id>/', views.stripe_payment, name='stripe-payment'),
    path('stripe-payment-verify/<order_id>/', views.stripe_payment_verify, name='stripe-payment-verify'),

    path('paystack-payment-verify/<order_id>/', views.paystack_payment_verify, name='paystack-payment-verify'),
    path('flutterwave-payment-callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave-payment-callback'),

    path('razorpay-payment-verify/<order_id>/', views.razorpay_payment_verify, name='razorpay-payment-verify'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),
]

customer/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from store.models import Product
from userauths.models import User

TYPE = (
    ('New Order', 'New Order'),
    ('Item Shipped', 'Item Shipped'),
    ('Item Delivered', 'Item Delivered'),
)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishlist')

    class Meta:
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        if self.product.name:
            return self.product.name
        else:
            return 'Wishlist'
        

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=200, null=True, blank=True, default=None)

    mobile = PhoneNumberField()
    email = models.EmailField()

    country = models.CharField(max_length=100, null=True, blank=True, default=None)
    state = models.CharField(max_length=100, null=True, blank=True, default=None)
    city = models.CharField(max_length=100, null=True, blank=True, default=None)
    
    address = models.CharField(max_length=150, null=True, blank=True, default=None)
    zip_code = models.CharField(max_length=50, null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.address
    

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_notification', null=True)
    
    type = models.CharField(max_length=100, choices=TYPE, default=None)
    seen = models.BooleanField(default=False)

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'

    def __str__(self):
        return self.type

customer/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.db import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password

from plugins.paginate_queryset import paginate_queryset
from store import models as store_models
from customer import models as customer_models


@login_required
def dashboard(request):
    orders_list = store_models.Order.objects.filter(customer=request.user)
    orders = paginate_queryset(request, orders_list, 1)

    total_spent = store_models.Order.objects.filter(customer=request.user).aggregate(total = models.Sum('total'))['total']
    notis = customer_models.Notification.objects.filter(user=request.user, seen=False)
    addresses = customer_models.Address.objects.filter(user=request.user)
    profile = request.user.profile

    context = {
        'orders_list': orders_list,
        'orders': orders,
        'total_spent': total_spent,
        'notis': notis,
        'addresses': addresses,
        'profile': profile,
    }

    return render(request, 'customer/dashboard.html', context)


@login_required
def wishlist(request):
    wishlist_list = customer_models.Wishlist.objects.filter(user=request.user)
    wishlist = paginate_queryset(request, wishlist_list, 1)

    context = {
        'wishlist_list': wishlist_list,
        'wishlist': wishlist,
    }

    return render(request, 'customer/wishlist.html', context)


@login_required
def remove_from_wishlist(request, id):
    wishlist = customer_models.Wishlist.objects.get(user=request.user, id=id)
    wishlist.delete()

    messages.success(request, 'Item removed from wishlist')
    return redirect('customer:wishlist')


@login_required
def add_to_wishlist(request, id):
    if request.user.is_authenticated:
        product = store_models.Product.objects.filter(id=id).first()
        wishlist_exists = customer_models.Wishlist.objects.filter(product=product, user=request.user).first()

        if not wishlist_exists:
            customer_models.Wishlist.objects.create(user=request.user, product=product)
        
        wishlist = customer_models.Wishlist.objects.filter(user=request.user)
        return JsonResponse({'message': 'Item added to wishlist', 'wishlist_count': wishlist.count()})
    else:
        return JsonResponse({'message': 'User is not logged in', 'wishlist_count': '0'})
    

@login_required
def mark_notification_seen(request, id):
    noti = customer_models.Notification.objects.get(user=request.user, id=id)
    noti.seen = True
    noti.save()

    messages.success(request, 'Notification maked as seen')
    return redirect('customer:dashboard')


@login_required
def address_detail(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)

    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        mobile = request.POST.get('mobile')
        email = request.POST.get('email')
        country = request.POST.get('country')
        state = request.POST.get('state')
        city = request.POST.get('city')
        address_location = request.POST.get('address')
        zip_code = request.POST.get('zip_code')

        address.full_name = full_name
        address.mobile = mobile
        address.email = email
        address.country = country
        address.state = state
        address.city = city
        address.address = address_location
        address.zip_code = zip_code
        address.save()

        messages.success(request, 'Address was updated successfully')
        return redirect('customer:dashboard')
    
    context = {
        'address': address
    }

    return render(request, 'customer/address-detail.html', context)


@login_required
def address_create(request):
    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        mobile = request.POST.get('mobile')
        email = request.POST.get('email')
        country = request.POST.get('country')
        state = request.POST.get('state')
        city = request.POST.get('city')
        address_location = request.POST.get('address')
        zip_code = request.POST.get('zip_code')

        customer_models.Address.objects.create(
            user = request.user,
            full_name = full_name,
            mobile = mobile,
            email = email,
            country = country,
            state = state,
            city = city,
            address = address_location,
            zip_code = zip_code,
        )

        messages.success(request, 'Address was created successfully')
        return redirect('customer:dashboard')

    return render(request, 'customer/address-create.html')


@login_required
def delete_address(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)
    address.delete()

    messages.success(request, 'Address was deleted successfully')
    return redirect('customer:dashboard')


@login_required
def update_profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        image = request.FILES.get('image')
        full_name = request.POST.get('full_name')
        mobile = request.POST.get('mobile')

        if image:
            profile.image = image

        profile.full_name = full_name
        profile.mobile = mobile
        profile.save()

        messages.success(request, 'Profile Updated Successfully')
        return redirect('customer:dashboard')

    return redirect('customer:dashboard')


@login_required
def change_password(request):
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        confirm_new_password = request.POST.get('confirm_new_password')

        if confirm_new_password != new_password:
            messages.error(request, 'Confirm password and new password Does Not Match')
            return redirect('customer:change-password')

        if check_password(old_password, request.user.password):
            request.user.set_password(new_password)
            request.user.save()
            messages.success(request, 'Password Changed Successfully')
            return redirect('customer:dashboard')
        else:
            messages.error(request, 'Old password is Incorrect')
            return redirect('customer:change-password')
    
    
    return redirect('customer:dashboard')

templates/customer/address-create.html
{% extends "partials/base.html" %}
{% block content %}
{% load static %}

<style>
    .form-row {
    display: flex;
    gap: 10px;
}

.form-row .form-group {
    flex: 1;
}

</style>

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                    <div class="row">
                        <div class="col-lg-6 pr-30 d-none d-lg-block">
                            <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                        </div>
                        <div class="col-lg-6 col-md-8">
                            <div class="login_wrap widget-taber-content background-white">
                                <div class="padding_eight_all bg-white">
                                    <div class="heading_s1">
                                        <h1 class="mb-5">Create an Address</h1>
                                        <p class="mb-30">Already have an account? <a href="page-login.html">Login</a></p>
                                    </div>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" required="" name="full_name" placeholder="Full Name" value="{{request.user.profile.full_name}}"/>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" required="" name="email" placeholder="Email" value="{{request.user.email}}"/>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <input type="text" required="" name="mobile" placeholder="Mobile" value="{{request.user.profile.mobile}}"/>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" required="" name="address" placeholder="Address" />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <input type="text" required="" name="city" placeholder="City" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" required="" name="state" placeholder="State" />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group">
                                                <input type="text" required="" name="country" placeholder="Country" />
                                            </div>
                                            <div class="chek-form">
                                                <input type="text" required="" name="zip_code" placeholder="Zip code *" />
                                            </div>
                                        </div>
                                        <div class="login_footer form-group mb-50">
                                            <div class="chek-form">
                                                <div class="custome-checkbox">
                                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                    <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                                </div>
                                            </div>
                                            <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Learn more</a>
                                        </div>
                                        <div class="form-group mb-30">
                                            <a href="{% url "customer:dashboard" %}"></a>
                                            <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Submit &amp; Create</button>
                                        </div>
                                        <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy</p>
                                    </form>                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/customer/address-detail.html
{% extends "partials/base.html" %}
{% block content %}
{% load static %}

<div class="row" style="padding: 10%;">
    <div class="card">
        <div class="card-header" style="background-color: white;">
            <h5>Account Details</h5>
        </div>
        <div class="card-body">
            <form method="post" name="enq">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-md-6">
                        <label>Full Name <span class="required">*</span></label>
                        <input required="" class="form-control" name="full_name" type="text" value="{{address.full_name}}"/>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Email <span class="required">*</span></label>
                        <input required="" class="form-control" name="email" type="email" value="{{address.email}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Mobile Number <span class="required">*</span></label>
                        <input required="" class="form-control" name="mobile" type="text" value="{{address.mobile}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Address <span class="required">*</span></label>
                        <input required="" class="form-control" name="address" type="text" value="{{address.address}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>City <span class="required">*</span></label>
                        <input required="" class="form-control" name="city" type="text" value="{{address.city}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>State <span class="required">*</span></label>
                        <input required="" class="form-control" name="state" type="text" value="{{address.state}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Country <span class="required">*</span></label>
                        <input required="" class="form-control" name="country" type="text" value="{{address.country}}"/>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Zip <span class="required">*</span></label>
                        <input required="" class="form-control" name="zip_code" type="text" value="{{address.zip_code}}"/>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-fill-out submit font-weight-bold" name="submit" value="Submit">Save Change</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/customer/sidebar.html
<div class="col-md-3">
    <div class="dashboard-menu">
        <ul class="nav flex-column" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="dashboard-tab" data-bs-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="false"><i class="fi-rs-settings-sliders mr-10"></i>Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="orders-tab" data-bs-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false"><i class="fi-rs-shopping-bag mr-10"></i>Orders</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="orders-tab" data-bs-toggle="tab" href="#notifications" role="tab" aria-controls="orders" aria-selected="false"><i class="fa-regular fa-bell"></i>&nbsp;&nbsp;Notifications</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="track-orders-tab" data-bs-toggle="tab" href="#track-orders" role="tab" aria-controls="track-orders" aria-selected="false"><i class="fi-rs-shopping-cart-check mr-10"></i>Track Your Order</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="addresses-tab" data-bs-toggle="tab" href="#addresses" role="tab" aria-controls="addresses" aria-selected="false"><i class="fi-rs-shopping-cart-check mr-10"></i>My Addresses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="account-detail-tab" data-bs-toggle="tab" href="#account-detail" role="tab" aria-controls="account-detail" aria-selected="true"><i class="fi-rs-user mr-10"></i>Account details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="change-password-tab" data-bs-toggle="tab" href="#change-password" role="tab" aria-controls="change-password" aria-selected="true"><i class="fi-rs-user mr-10"></i>Change Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "userauths:sign-out" %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
            </li>
        </ul>
    </div>
</div>

templates/customer/wishlist.html
{% extends "partials/base.html" %}
{% block content %}
{% load static %}
{% load humanize %}

<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url "store:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop <span></span> Fillter
            </div>
        </div>
    </div>
    <div class="container mb-30 mt-50">
        <div class="row">
            <div class="col-xl-10 col-lg-12 m-auto">
                <div class="mb-50">
                    <h1 class="heading-2 mb-10">Your Wishlist</h1>
                    <h6 class="text-body">There are <span class="text-brand">{{wishlist.count}}</span> product{{wishlist_list.count|pluralize}} in this list</h6>
                </div>
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                <th class="custome-checkbox start pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                    <label class="form-check-label" for="exampleCheckbox11"></label>
                                </th>
                                <th scope="col" colspan="2">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Stock Status</th>
                                <th scope="col">Action</th>
                                <th scope="col" class="end">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in wishlist %}
                            <tr class="pt-30">
                                <td class="custome-checkbox pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                    <label class="form-check-label" for="exampleCheckbox1"></label>
                                </td>
                                <td class="image product-thumbnail pt-40"><img src="{{i.product.image.url}}" alt="#" /></td>
                                <td class="product-des product-name">
                                    <h6><a class="product-name mb-10" href="{% url "store:product-detail" i.product.slug %}">{{i.product.name}}</a></h6>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: {{i.product.average_rating_percentage}}%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> ({{i.product.average_rating|floatformat:1}})</span>
                                    </div>
                                </td>
                                <td class="price" data-title="Price">
                                    <h3 class="text-brand">${{i.product.price}}</h3>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <span class="stock-status in-stock mb-0"> In Stock </span>
                                </td>
                                <td class="text-right" data-title="Cart">
                                    <input type="hidden" name="quantity" id="quantity" class="qty-val quantity" value="1" min="1" max="{{i.product.stock}}" required>
                                    <a class="add" data-id="{{i.product.id}}"><i class="fi-rs-shopping-cart mr-5">Add To Cart</i></a>
                                </td>
                                <td class="action text-center" data-id="{{i.product.id}}" data-title="Remove">
                                    <a href="{% url "customer:remove-from-wishlist" i.id %}" class="text-body"><i class="fi-rs-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            {% if wishlist.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{wishlist.previous_page_number}}"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            {% endif %}

                            {% for num in wishlist.paginator.page_range %}
                            <li class="page-item {% if wishlist.number == num %}active{% endif %}">
                                <a class="page-link" href="?page={{num}}">{{num}}</a>
                            </li>
                            {% endfor %}

                            {% if wishlist.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{wishlist.next_page_number}}"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}