eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from store import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user/', include('userauths.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    # HomePage
    path('', views.index, name='index'),

    # Category
    path('category/<slug>/', views.category, name='category'),

    # Product Detail
    path('product-detail/<slug>/', views.product_detail, name='product-detail'),

    # Add To Cart, Cart, Delete Cart Item
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),
    path('delete-cart-item/', views.delete_cart_item, name='delete-cart-item'),

    # Create Order, Checkout
    path('create-order/', views.create_order, name='create-order'),
    path('checkout/<order_id>/', views.checkout, name='checkout'),
    path('coupon-apply/<order_id>/', views.coupon_apply, name='coupon-apply'),

    # Payment
    path('paypal-payment-verify/<order_id>/', views.paypal_payment_verify, name='paypal-payment-verify'),
    path('payment-status/<order_id>/', views.payment_status, name='payment-status'),
    
    path('stripe-payment/<order_id>/', views.stripe_payment, name='stripe-payment'),
    path('stripe-payment-verify/<order_id>/', views.stripe_payment_verify, name='stripe-payment-verify'),

    path('paystack-payment-verify/<order_id>/', views.paystack_payment_verify, name='paystack-payment-verify'),
    path('flutterwave-payment-callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave-payment-callback'),

    path('razorpay-payment-verify/<order_id>/', views.razorpay_payment_verify, name='razorpay-payment-verify'),
]

store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import razorpay.errors

from store import models as store_models
from customer import models as customer_models
from vendor import models as vendor_models

from decimal import Decimal
from django.db.models import Q, Avg, Sum

from django.contrib import messages
from django.conf import settings

import requests
import stripe
import razorpay

from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from plugins.tax_calculation import tax_calculation
from plugins.service_fee import calculate_service_fee
from plugins.exchange_rate import convert_usd_inr, convert_usd_kobo, convert_usd_ngn


stripe.api_key = settings.STRIPE_SECRET_KEY
razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))


def index(request):
    products = store_models.Product.objects.filter(status='Published', featured=True)
    categories = store_models.Category.objects.all()[:4]

    context = {
        'products': products,
        'new_products': store_models.Product.objects.filter(status='Published', featured=True).order_by('-date')[:4],
        'categories': categories,
    }

    return render(request, 'store/index.html', context)


def category(request, slug):
    category = store_models.Category.objects.get(slug=slug)
    products = store_models.Product.objects.filter(category=category, status='Published')

    context = {
        'category': category,
        'products': products,
    }

    return render(request, 'store/category.html', context)


def product_detail(request, slug):
    product = store_models.Product.objects.get(status='Published', slug=slug)
    related_product = store_models.Product.objects.filter(category=product.category, status='Published').exclude(id=product.id)

    # variant_items = []
    # for variant in product.variants():
    #     for item in variant.variant_items.all():
    #         if item.title == 'Weight' or item.title == 'weight' or item.title =='Size' or item.title == 'size':
    #             item.description_list = item.description.split(',')
    #             variant_items.append(item)

    context = {
        'product': product,
        'related_product': related_product,
        # 'variant_items': variant_items,
    }

    return render(request, 'store/product-detail.html', context)


def add_to_cart(request):
    id = request.GET.get('id')
    qty = request.GET.get('qty')
    cart_id = request.GET.get('cart_id')

    request.session['cart_id'] = cart_id

    if not id or not qty or not cart_id:
        return JsonResponse({'error': 'No id, qty or cart_id'}, status=400)
    
    try:
        product = store_models.Product.objects.get(status='Published', id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({'error': 'Product not found'}, status=400)
    
    existing_cart_items = store_models.Cart.objects.filter(cart_id=cart_id, product=product).first()
    if int(qty) > product.stock:
        return JsonResponse({'error': 'Qty exceed current stock amount'}, status=404)
    
    if not existing_cart_items:
        cart = store_models.Cart()
        cart.product = product
        cart.qty = qty
        cart.price = product.price
        cart.sub_total = Decimal(product.price) * Decimal(qty)
        cart.shipping = Decimal(product.shipping)
        cart.total = cart.sub_total + cart.shipping
        cart.user = request.user if request.user.is_authenticated else None
        cart.cart_id = cart_id
        cart.save()

        message = 'Item added to cart'
    else:
        existing_cart_items.product = product
        existing_cart_items.qty = qty
        existing_cart_items.price = product.price
        existing_cart_items.sub_total = Decimal(product.price) * Decimal(qty)
        existing_cart_items.shipping = Decimal(product.shipping)
        existing_cart_items.total = existing_cart_items.sub_total + existing_cart_items.shipping
        existing_cart_items.user = request.user if request.user.is_authenticated else None
        existing_cart_items.cart_id = cart_id
        existing_cart_items.save()

        message = 'Cart Updated'

    total_cart_items = store_models.Cart.objects.filter(Q(cart_id=cart_id))
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total=Sum('sub_total'))['sub_total']

    return JsonResponse({
        'message': message,
        'total_cart_items': total_cart_items.count(),
        'cart_sub_total': '{:,.2f}'.format(cart_sub_total),
        'item_sub_total': '{:,.2f}'.format(existing_cart_items.sub_total) if existing_cart_items else '{:,.2f}'.format(cart.sub_total),
    })


def cart(request):
    if 'cart_id' in request.session:
        cart_id = request.session['cart_id']
    else:
        cart_id = None

    items = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user) if request.user.is_authenticated else Q(cart_id=cart_id))
    cart_sub_total = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user) if request.user.is_authenticated else Q(cart_id=cart_id)).aggregate(sub_total = Sum('sub_total'))['sub_total']

    try:
        addresses = customer_models.Address.objects.filter(user=request.user)
    except:
        addresses = None

    if not items:
        messages.warning(request, 'No items in cart')
        return redirect('store:index')
    
    context = {
        'items': items,
        'cart_sub_total': cart_sub_total,
        'addresses': addresses,
    }

    return render(request, 'store/cart.html', context)


def delete_cart_item(request):
    id = request.GET.get('id')
    item_id = request.GET.get('item')
    cart_id = request.GET.get('cart_id')

    print('Product ID: ', id)
    print('Item ID: ', item_id)
    print('Cart ID: ', cart_id)

    if not id or not item_id or not cart_id:
        return JsonResponse({'error': 'Item or Product Id not found'}, status=400)
    
    try:
        product = store_models.Product.objects.get(status='Published', id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({'error': 'Product not found'}, status=404)
    
    item = store_models.Cart.objects.get(product=product, id=item_id)
    item.delete()

    total_cart_items = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user))
    cart_sub_total = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user)).aggregate(sub_total = Sum('sub_total'))['sub_total']

    return JsonResponse({
        'message': 'Item Deleted',
        'total_cart_items' : total_cart_items.count(),
        'cart_sub_total': '{:,.2f}'.format(cart_sub_total) if cart_sub_total else 0.00
    })


def create_order(request):
    if request.method == 'POST':
        address_id = request.POST.get('address')

        if not address_id:
            messages.warning(request, 'Please create or select an address to continue')
            return redirect('store:cart')
        
        address = customer_models.Address.objects.filter(user=request.user, id=address_id).first()

        if 'cart_id' in request.session:
            cart_id = request.session['cart_id']
        else:
            cart_id = None
        
        items = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user) if request.user.is_authenticated else Q(cart_id=cart_id))
        cart_sub_total = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user) if request.user.is_authenticated else Q(cart_id=cart_id)).aggregate(sub_total = Sum('sub_total'))['sub_total']
        cart_shipping_total = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(user=request.user) if request.user.is_authenticated else Q(cart_id=cart_id)).aggregate(shipping = Sum('shipping'))['shipping']

        order = store_models.Order()
        order.sub_total = cart_sub_total
        order.customer = request.user
        order.address = address
        order.shipping = cart_shipping_total
        order.tax = tax_calculation(address.country, cart_sub_total)
        order.total = order.sub_total + order.shipping + Decimal(order.tax)
        order.service_fee = calculate_service_fee(order.total)
        order.total += order.service_fee
        order.initial_total = order.total
        order.save()

        for i in items:
            store_models.OrderItem.objects.create(
                order = order,
                product = i.product,
                qty = i.qty,
                price = i.price,
                sub_total = i.sub_total,
                shipping = i.shipping,
                tax = tax_calculation(address.country, i.sub_total),
                total = i.total,
                initial_total = i.total,
                vendor = i.product.vendor,
            )

            order.vendors.add(i.product.vendor)

    return redirect('store:checkout', order.order_id)


def clear_cart_items(request):
    try:
        cart_id = request.session['cart_id']
        store_models.Cart.objects.filter(cart_id=cart_id).delete()
    except:
        pass

    return


def checkout(request, order_id):
    order = store_models.Order.objects.get(order_id=order_id)

    amount_in_inr = convert_usd_inr(order.total)
    amount_in_kobo = convert_usd_kobo(order.total)
    amount_in_ngn = convert_usd_ngn(order.total)

    try:
        razorpay_order = razorpay_client.order.create({
            'amount': int(amount_in_inr),
            'currency': 'INR',
            'payment_capture': '1'
        })
    except:
        razorpay_order = None


    context = {
        'order': order,
        'razorpay_order_id': razorpay_order['id'] if razorpay_order else None,
        'amount_in_inr': amount_in_inr,
        'amount_in_kobo': amount_in_kobo,
        'amount_in_ngn': amount_in_ngn,

templates/store/cart.html
{% extends "partials/base.html" %}
{% block content %}
{% load static %}
{% load humanize %}


<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url "store:index" %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Cart
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Cart</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand total_cart_items">{{total_cart_items}}</span> product{{total_cart_items|pluralize}} in your cart</h6>
                    <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                </div>
            </div>
        </div>
        <form action="{% url "store:create-order" %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input type="hidden" name="">
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in items %}
                                <tr class="pt-30 item_div_{{i.id}}">
                                    <td class="custome-checkbox pl-30">
                                        <input type="hidden" name="">
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{i.product.image.url}}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url "store:product-detail" i.product.slug %}">{{i.product.name}}</a> by <a href="">({{i.product.vendor.profile.full_name}})</a></h6>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width:{{i.product.average_rating_percentage}}%">
                                                </div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> ({{i.product.average_rating|floatformat:1}})</span>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">${{i.price|intcomma}} </h4>
                                    </td>
                                    <td class="text-center detail-info">
                                        <div class="detail-extralink mr-15">
                                            <div class="detail-qty border radius">
                                                <input 
                                                class="qty-val update_cart_qty" 
                                                type="number" 
                                                name="quantity" 
                                                id="quantity" 
                                                value="{{i.qty}}" 
                                                min="1" 
                                                max="{{i.product.stock}}" 
                                                data-update_type="update" 
                                                data-item_id="{{i.id}}"
                                                data-product_id="{{i.product.id}}"
                                                required>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand">$<span class="item_sub_total_{{i.id}}">{{i.sub_total|intcomma}}</span></h4>
                                    </td>
                                    <td class="action text-center">
                                        <a 
                                        class="text-body delete_cart_item" 
                                        data-item_id="{{i.id}}" 
                                        data-product_id="{{i.product.id}}">
                                        <i class="fi-rs-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <div class="cart-action d-flex justify-content-between">
                        <a class="btn "><i class="fi-rs-arrow-left mr-10"></i>Continue Shopping</a>
                        <a href="{% url "store:cart" %}" class="btn  mr-10 mb-sm-15"><i class="fi-rs-refresh mr-10"></i>Update Cart</a>
                    </div>
                    <div class="row mt-50">
                        {% for i in addresses %}
                        <div class="col-lg-6" style="margin-bottom: 30px;">
                            <div class="card mb-3 mb-lg-0">
                                <div class="card-header">
                                    <h3 class="mb-0">Billing Address</h3>
                                </div>
                                <div class="card-body">
                                    <address>
                                        <strong>Full Name: </strong>{{i.full_name}}<br />
                                        <strong>Email: </strong>{{i.email}},<br />
                                        <strong>Phone Number: </strong>{{i.mobile}}. <br /><strong>Address: </strong>{{i.address}}
                                    </address>
                                    <p><strong>City: </strong>{{i.city}}</p>
                                    <p><strong>State: </strong>{{i.state}}</p>
                                    <p><strong>Country: </strong>{{i.country}}</p>
                                    <input class="form-check-input" type="checkbox" name="address" id="address{{i.id}}" value="{{i.id}}">
                                    <label for="address{{i.id}}">Select Address</label><br>
                                    <a href="#" class="btn-small">Edit</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">$<span class="cart_sub_total">{{cart_sub_total|intcomma}}</span></h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Free</h4></td> </tr> <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Estimate for</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">United Kingdom</h4></td> </tr> <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">$<span class="cart_sub_total">{{cart_sub_total|intcomma}}</span></h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                    </div>
                </div>
            </div>
        </form>    
    </div>
</main>


{% endblock content %}